In [87]:
#Solver for 'Schnell', 'Leicht' & 'Mittel'

from random import choice
import pandas as pd

s = pd.read_csv('Sudoku.csv', sep = ';')
sudoku = s.copy()
sudoku.fillna(0, inplace=True)
sudoku = sudoku.astype('int64')

perfect = {1, 2, 3, 4, 5, 6, 7, 8, 9}
loop = 1

ex = []

while loop == 1:
    sudoku_h = sudoku.values.tolist()
    sudoku_h1 = sudoku_h[0]
    sudoku_h2 = sudoku_h[1]
    sudoku_h3 = sudoku_h[2]
    sudoku_h4 = sudoku_h[3]
    sudoku_h5 = sudoku_h[4]
    sudoku_h6 = sudoku_h[5]
    sudoku_h7 = sudoku_h[6]
    sudoku_h8 = sudoku_h[7]
    sudoku_h9 = sudoku_h[8]
    sudoku_v1 = sudoku['a'].values.tolist()
    sudoku_v2 = sudoku['b'].values.tolist()
    sudoku_v3 = sudoku['c'].values.tolist()
    sudoku_v4 = sudoku['d'].values.tolist()
    sudoku_v5 = sudoku['e'].values.tolist()
    sudoku_v6 = sudoku['f'].values.tolist()
    sudoku_v7 = sudoku['g'].values.tolist()
    sudoku_v8 = sudoku['h'].values.tolist()
    sudoku_v9 = sudoku['i'].values.tolist()
    sudoku_v = [sudoku_v1,sudoku_v2,sudoku_v3,sudoku_v4,sudoku_v5,sudoku_v6,sudoku_v7,sudoku_v8,sudoku_v9]
    sudoku_q1 = sudoku_v1[0:3] + sudoku_v2[0:3] + sudoku_v3[0:3]
    sudoku_q2 = sudoku_v4[0:3] + sudoku_v5[0:3] + sudoku_v6[0:3]
    sudoku_q3 = sudoku_v7[0:3] + sudoku_v8[0:3] + sudoku_v9[0:3]
    sudoku_q4 = sudoku_v1[3:6] + sudoku_v2[3:6] + sudoku_v3[3:6]
    sudoku_q5 = sudoku_v4[3:6] + sudoku_v5[3:6] + sudoku_v6[3:6]
    sudoku_q6 = sudoku_v7[3:6] + sudoku_v8[3:6] + sudoku_v9[3:6]
    sudoku_q7 = sudoku_v1[6:9] + sudoku_v2[6:9] + sudoku_v3[6:9]
    sudoku_q8 = sudoku_v4[6:9] + sudoku_v5[6:9] + sudoku_v6[6:9]
    sudoku_q9 = sudoku_v7[6:9] + sudoku_v8[6:9] + sudoku_v9[6:9]
    #sudoku_q =[sudoku_q1,sudoku_q2,sudoku_q3,sudoku_q4,sudoku_q5,sudoku_q6,sudoku_q7,sudoku_q8,sudoku_q9]
    for x in range(0,9):
        for y in range(0,9):
            ex.append(sudoku_h[x])
            ex.append(sudoku_v[y])
            if x in [0,1,2] and y in [0,1,2]:
                ex.append(sudoku_q1)
            if x in [0,1,2] and y in [3,4,5]:
                ex.append(sudoku_q2)
            if x in [0,1,2] and y in [6,7,8]:
                ex.append(sudoku_q3)
            if x in [3,4,5] and y in [0,1,2]:
                ex.append(sudoku_q4)
            if x in [3,4,5] and y in [3,4,5]:
                ex.append(sudoku_q5)
            if x in [3,4,5] and y in [6,7,8]:
                ex.append(sudoku_q6)
            if x in [6,7,8] and y in [0,1,2]:
                ex.append(sudoku_q7)
            if x in [6,7,8] and y in [3,4,5]:
                ex.append(sudoku_q8)
            if x in [6,7,8] and y in [6,7,8]:
                ex.append(sudoku_q9)
            ex_list = list(set(sum(ex, [])))
            if 0 in ex_list:
                ex_list.remove(0)
            if sudoku.loc[x][y] == 0:
                if len(ex_list) == 8:
                    sudoku.loc[x][y] = choice([z for z in range(1,10) if z not in ex_list])
            #print(x,y, ex)
            ex = []
            #print(sudoku)
    if set(sudoku_h[0]) == perfect and set(sudoku_h[1]) == perfect and set(sudoku_h[2]) == perfect \
    and set(sudoku_h[3]) == perfect and set(sudoku_h[4]) == perfect and set(sudoku_h[5]) == perfect \
    and set(sudoku_h[6]) == perfect and set(sudoku_h[7]) == perfect and set(sudoku_h[8]) == perfect: 
        print(sudoku.to_string(index=False, header=False))
        sudoku.to_csv('Sudoku-Solution.csv')
        break

4 9 6 5 3 8 7 2 1
1 8 7 6 9 2 3 4 5
3 5 2 1 4 7 6 8 9
5 6 9 2 8 3 4 1 7
8 3 1 4 7 5 2 9 6
2 7 4 9 6 1 8 5 3
7 1 3 8 5 4 9 6 2
9 4 5 7 2 6 1 3 8
6 2 8 3 1 9 5 7 4

In [ ]:
#Andere Herangehensweise? Sudokubrett ist ein Dataframe bestehend aus x Listen, jede Liste für einen Index (der gleich 0) 
# und enthält alle Werte, die dieses Feld NICHT MEHR annehmen kann (wegen h,v,q). Wenn Länge der Liste gleich 8,
# dann wird fehlender Wert eingetragen
# ADDON:
# Darüber hinaus werden wieder Listen h, v, q erstellt. Wenn ein Wert in einer dieser Listen noch nicht eingetragen ist
# und in n-1 Listen enthalten (und somit für dieses jeweilige Feld nicht mehr annehmbar) ist, wird dieser Wert in 
# das einzige verbleibende freie Feld eingetragen

In [106]:
#Solver for 'Experte'

import pandas as pd

s = pd.read_csv('Sudoku.csv', sep = ';')
sudoku = s.copy()
sudoku.fillna(0, inplace=True)
sudoku = sudoku.astype('int64')
perfect = [1, 2, 3, 4, 5, 6, 7, 8, 9]

sudoku = sudoku.rename(columns={'a': 0,'b': 1,'c': 2,'d': 3,'e': 4,'f': 5,'g': 6,'h': 7,'i': 8})
s = sudoku.to_dict('index')
s[0][1] = [4,2,1]
type(s[0][1]) == list

True

In [2]:
#Solver for 'Experte'

from random import choice
import pandas as pd


s = pd.read_csv('Sudoku.csv', sep = ';')
sudoku = s.copy()
perfect = {1, 2, 3, 4, 5, 6, 7, 8, 9}
loop = 1

ex = []

while loop == 1:
    sudoku_h = sudoku.values.tolist()
    sudoku_h1 = sudoku_h[0]
    sudoku_h2 = sudoku_h[1]
    sudoku_h3 = sudoku_h[2]
    sudoku_h4 = sudoku_h[3]
    sudoku_h5 = sudoku_h[4]
    sudoku_h6 = sudoku_h[5]
    sudoku_h7 = sudoku_h[6]
    sudoku_h8 = sudoku_h[7]
    sudoku_h9 = sudoku_h[8]
    sudoku_v1 = sudoku['a'].values.tolist()
    sudoku_v2 = sudoku['b'].values.tolist()
    sudoku_v3 = sudoku['c'].values.tolist()
    sudoku_v4 = sudoku['d'].values.tolist()
    sudoku_v5 = sudoku['e'].values.tolist()
    sudoku_v6 = sudoku['f'].values.tolist()
    sudoku_v7 = sudoku['g'].values.tolist()
    sudoku_v8 = sudoku['h'].values.tolist()
    sudoku_v9 = sudoku['i'].values.tolist()
    sudoku_v = [sudoku_v1,sudoku_v2,sudoku_v3,sudoku_v4,sudoku_v5,sudoku_v6,sudoku_v7,sudoku_v8,sudoku_v9]
    sudoku_q1 = sudoku_v1[0:3] + sudoku_v2[0:3] + sudoku_v3[0:3]
    sudoku_q2 = sudoku_v4[0:3] + sudoku_v5[0:3] + sudoku_v6[0:3]
    sudoku_q3 = sudoku_v7[0:3] + sudoku_v8[0:3] + sudoku_v9[0:3]
    sudoku_q4 = sudoku_v1[3:6] + sudoku_v2[3:6] + sudoku_v3[3:6]
    sudoku_q5 = sudoku_v4[3:6] + sudoku_v5[3:6] + sudoku_v6[3:6]
    sudoku_q6 = sudoku_v7[3:6] + sudoku_v8[3:6] + sudoku_v9[3:6]
    sudoku_q7 = sudoku_v1[6:9] + sudoku_v2[6:9] + sudoku_v3[6:9]
    sudoku_q8 = sudoku_v4[6:9] + sudoku_v5[6:9] + sudoku_v6[6:9]
    sudoku_q9 = sudoku_v7[6:9] + sudoku_v8[6:9] + sudoku_v9[6:9]
    #sudoku_q =[sudoku_q1,sudoku_q2,sudoku_q3,sudoku_q4,sudoku_q5,sudoku_q6,sudoku_q7,sudoku_q8,sudoku_q9]
    for x in range(0,9):
        for y in range(0,9):
            ex.append(sudoku_h[x])
            ex.append(sudoku_v[y])
            if x in [0,1,2] and y in [0,1,2]:
                ex.append(sudoku_q1)
            if x in [0,1,2] and y in [3,4,5]:
                ex.append(sudoku_q2)
            if x in [0,1,2] and y in [6,7,8]:
                ex.append(sudoku_q3)
            if x in [3,4,5] and y in [0,1,2]:
                ex.append(sudoku_q4)
            if x in [3,4,5] and y in [3,4,5]:
                ex.append(sudoku_q5)
            if x in [3,4,5] and y in [6,7,8]:
                ex.append(sudoku_q6)
            if x in [6,7,8] and y in [0,1,2]:
                ex.append(sudoku_q7)
            if x in [6,7,8] and y in [3,4,5]:
                ex.append(sudoku_q8)
            if x in [6,7,8] and y in [6,7,8]:
                ex.append(sudoku_q9)
            ex_list = list(set(sum(ex, [])))
            if 0 in ex_list:
                ex_list.remove(0)
            if sudoku.loc[x][y] == 0:
                if len(ex_list) == 8:
                    sudoku.loc[x][y] = choice([z for z in range(1,10) if z not in ex_list])
            #print(x,y, ex)
            ex = []
            #print(sudoku)
    if set(sudoku_h[0]) == perfect and set(sudoku_h[1]) == perfect and set(sudoku_h[2]) == perfect \
    and set(sudoku_h[3]) == perfect and set(sudoku_h[4]) == perfect and set(sudoku_h[5]) == perfect \
    and set(sudoku_h[6]) == perfect and set(sudoku_h[7]) == perfect and set(sudoku_h[8]) == perfect: 
        print(sudoku.to_string(index=False, header=False))
        sudoku.to_csv('Sudoku-Solution.csv')
        break

4 9 6 5 3 8 7 2 1
1 8 7 6 9 2 3 4 5
3 5 2 1 4 7 6 8 9
5 6 9 2 8 3 4 1 7
8 3 1 4 7 5 2 9 6
2 7 4 9 6 1 8 5 3
7 1 3 8 5 4 9 6 2
9 4 5 7 2 6 1 3 8
6 2 8 3 1 9 5 7 4

In [46]:
sudoku

   a  b  c  d  e  f  g  h  i
0  4  0  0  0  0  0  0  0  1
1  0  0  0  0  9  2  0  0  5
2  3  0  0  1  0  0  0  8  0
3  0  0  9  0  8  0  0  1  7
4  0  0  1  4  0  5  0  0  0
5  0  0  0  0  6  0  8  0  3
6  0  0  0  0  0  4  9  6  2
7  0  0  5  7  0  0  0  3  0
8  6  2  8  0  0  9  0  7  0

In [81]:
#sudoku = sudoku.rename(columns={'a': 0,'b': 1,'c': 2,'d': 3,'e': 4,'f': 5,'g': 6,'h': 7,'i': 8})
#sudoku.index.name = 'ID'
sudoku

    0  1  2  3  4  5  6  7  8
ID
0   4  0  0  0  0  0  0  0  1
1   0  0  0  0  9  2  0  0  5
2   3  0  0  1  0  0  0  8  0
3   0  0  9  0  8  0  0  1  7
4   0  0  1  4  0  5  0  0  0
5   0  0  0  0  6  0  8  0  3
6   0  0  0  0  0  4  9  6  2
7   0  0  5  7  0  0  0  3  0
8   6  2  8  0  0  9  0  7  0

In [99]:
sudoku = sudoku.rename(columns={'a': 0,'b': 1,'c': 2,'d': 3,'e': 4,'f': 5,'g': 6,'h': 7,'i': 8})
s = sudoku.to_dict('index')
s[0][1] = []
s

{0: {0: 4, 1: [], 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1},
 1: {0: 0, 1: 0, 2: 0, 3: 0, 4: 9, 5: 2, 6: 0, 7: 0, 8: 5},
 2: {0: 3, 1: 0, 2: 0, 3: 1, 4: 0, 5: 0, 6: 0, 7: 8, 8: 0},
 3: {0: 0, 1: 0, 2: 9, 3: 0, 4: 8, 5: 0, 6: 0, 7: 1, 8: 7},
 4: {0: 0, 1: 0, 2: 1, 3: 4, 4: 0, 5: 5, 6: 0, 7: 0, 8: 0},
 5: {0: 0, 1: 0, 2: 0, 3: 0, 4: 6, 5: 0, 6: 8, 7: 0, 8: 3},
 6: {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 4, 6: 9, 7: 6, 8: 2},
 7: {0: 0, 1: 0, 2: 5, 3: 7, 4: 0, 5: 0, 6: 0, 7: 3, 8: 0},
 8: {0: 6, 1: 2, 2: 8, 3: 0, 4: 0, 5: 9, 6: 0, 7: 7, 8: 0}}